/* 
  Pizza Edition Games - Local Icon Database
  Using local assets/images/ icons | No "**" Stars | AdSense Safe
*/

const gamesData = [
    { id: "minecraft-ish-mmo", title: "Minecraft-ish MMO", category: "Adventure", image: "assets/images/minecraft-ish-mmo.png", embed: "https://play.gamepix.com/minecraft-ish-mmo/embed?sid=EE698", description: "Explore, build, and survive in this amazing Minecraft-inspired MMO. One of the top Pizza Edition Games for adventure lovers." },
    { id: "subway-surfer", title: "Subway Surfer", category: "Action", image: "assets/images/subway-surfer.png", embed: "https://play.gamepix.com/bus-and-subway-surfer/embed?sid=EE698", description: "Dash as fast as you can! Dodge the oncoming trains in this classic running game from Pizza Edition Games." },
    { id: "moto-x3m", title: "Moto X3M", category: "Sports", image: "assets/images/moto-x3m.png", embed: "https://play.gamepix.com/moto-x3m/embed?sid=EE698", description: "Master the stunts and race to the finish line in Moto X3M. A high-speed favorite on Pizza Edition Games." },
    { id: "temple-run-2", title: "Temple Run 2", category: "Adventure", image: "assets/images/temple-run-2.png", embed: "https://play.gamepix.com/temple-run-2/embed?sid=EE698", description: "The classic escape game is back! Run, jump, and slide in Temple Run 2, only on Pizza Edition Games." },
    { id: "slope", title: "Slope Run", category: "Action", image: "assets/images/slope.png", embed: "https://play.gamepix.com/slope/embed?sid=EE698", description: "Test your reflexes in Slope. How far can you roll? Find out on Pizza Edition Games." },
    { id: "2048", title: "2048 Puzzle", category: "Puzzle", image: "assets/images/2048.png", embed: "https://play.gamepix.com/2048/embed?sid=EE698", description: "Join the numbers and get to the 2048 tile! A brain-teasing puzzle from Pizza Edition Games." },
    { id: "crossy-road", title: "Crossy Road", category: "Action", image: "assets/images/crossy-road.png", embed: "https://play.gamepix.com/crossy-road/embed?sid=EE698", description: "Why did the chicken cross the road? Find out in Crossy Road on Pizza Edition Games." },
    { id: "flappy-bird", title: "Flappy Bird", category: "Action", image: "assets/images/flappy-bird.png", embed: "https://play.gamepix.com/flappy-bird/embed?sid=EE698", description: "Tap to fly and avoid the pipes in this addictive Flappy Bird clone on Pizza Edition Games." },
    { id: "cut-the-rope", title: "Cut the Rope", category: "Puzzle", image: "assets/images/cut-the-rope.png", embed: "https://play.gamepix.com/cut-the-rope/embed?sid=EE698", description: "Feed Om Nom by cutting the ropes and collecting stars in this hit Pizza Edition Games puzzle." },
    { id: "jetpack-joyride", title: "Jetpack Joyride", category: "Action", image: "assets/images/jetpack-joyride.png", embed: "https://play.gamepix.com/jetpack-joyride/embed?sid=EE698", description: "Suit up with cool jetpacks and fly through the lab in Jetpack Joyride on Pizza Edition Games." },
    { id: "among-us-online", title: "Among Us Online", category: "Strategy", image: "assets/images/among-us-online.png", embed: "https://play.gamepix.com/among-us-online/embed?sid=EE698", description: "Find the imposter or complete your tasks in Among Us Online, now on Pizza Edition Games." },
    { id: "stickman-hook", title: "Stickman Hook", category: "Action", image: "assets/images/stickman-hook.png", embed: "https://play.gamepix.com/stickman-hook/embed?sid=EE698", description: "Swing like a pro stickman through challenging levels in Stickman Hook on Pizza Edition Games." },
    { id: "tomb-mask", title: "Tomb of the Mask", category: "Action", image: "assets/images/tomb-mask.png", embed: "https://play.gamepix.com/tomb-of-the-mask/embed?sid=EE698", description: "Dash through neon mazes in Tomb of the Mask, a fast-paced arcade game from Pizza Edition Games." },
    { id: "vex-5", title: "Vex 5", category: "Action", image: "assets/images/vex-5.png", embed: "https://play.gamepix.com/vex-5/embed?sid=EE698", description: "Master the parkour levels in Vex 5. One of the most challenging Pizza Edition Games." },
    { id: "paper-io-2", title: "Paper.io 2", category: "Strategy", image: "assets/images/paper-io-2.png", embed: "https://play.gamepix.com/paper-io-2/embed?sid=EE698", description: "Conquer as much territory as possible in Paper.io 2 on Pizza Edition Games." },
    { id: "fireboy-watergirl-1", title: "Fireboy and Watergirl 1", category: "Puzzle", image: "assets/images/fireboy-watergirl-1.png", embed: "https://play.gamepix.com/fireboy-and-watergirl-1/embed?sid=EE698", description: "Solve puzzles together in the Forest Temple. A classic duo on Pizza Edition Games." },
    { id: "fruit-ninja", title: "Fruit Ninja", category: "Action", image: "assets/images/fruit-ninja.png", embed: "https://play.gamepix.com/fruit-ninja/embed?sid=EE698", description: "Slice fruit, avoid bombs! Master your ninja skills in Fruit Ninja on Pizza Edition Games." },
    { id: "shell-shockers", title: "Shell Shockers", category: "Action", image: "assets/images/shell-shockers.png", embed: "https://play.gamepix.com/shell-shockers/embed?sid=EE698", description: "The world's best egg-based shooter! Play Shell Shockers on Pizza Edition Games." },
    { id: "basketball-stars", title: "Basketball Stars", category: "Sports", image: "assets/images/basketball-stars.png", embed: "https://play.gamepix.com/basketball-stars/embed?sid=EE698", description: "Show off your basketball skills and dunk like a pro in Basketball Stars on Pizza Edition Games." },
    { id: "uno-online", title: "UNO Online", category: "Strategy", image: "assets/images/uno-online.png", embed: "https://play.gamepix.com/uno-online/embed?sid=EE698", description: "Play the world's favorite card game with friends in UNO Online on Pizza Edition Games." }
];
